# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movie_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13movie_service.proto\"\"\n\x0cMovieRequest\x12\x12\n\nmovie_list\x18\x01 \x01(\t\"U\n\tMovieList\x12\x0c\n\x04rank\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x12\n\nimDbRating\x18\x03 \x01(\t\x12\x17\n\x0fimDbRatingCount\x18\x04 \x01(\t\"+\n\rMovieResponse\x12\x1a\n\x06movies\x18\x01 \x03(\x0b\x32\n.MovieList25\n\x06Movies\x12+\n\nget_movies\x12\r.MovieRequest\x1a\x0e.MovieResponseb\x06proto3')



_MOVIEREQUEST = DESCRIPTOR.message_types_by_name['MovieRequest']
_MOVIELIST = DESCRIPTOR.message_types_by_name['MovieList']
_MOVIERESPONSE = DESCRIPTOR.message_types_by_name['MovieResponse']
MovieRequest = _reflection.GeneratedProtocolMessageType('MovieRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEREQUEST,
  '__module__' : 'movie_service_pb2'
  # @@protoc_insertion_point(class_scope:MovieRequest)
  })
_sym_db.RegisterMessage(MovieRequest)

MovieList = _reflection.GeneratedProtocolMessageType('MovieList', (_message.Message,), {
  'DESCRIPTOR' : _MOVIELIST,
  '__module__' : 'movie_service_pb2'
  # @@protoc_insertion_point(class_scope:MovieList)
  })
_sym_db.RegisterMessage(MovieList)

MovieResponse = _reflection.GeneratedProtocolMessageType('MovieResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOVIERESPONSE,
  '__module__' : 'movie_service_pb2'
  # @@protoc_insertion_point(class_scope:MovieResponse)
  })
_sym_db.RegisterMessage(MovieResponse)

_MOVIES = DESCRIPTOR.services_by_name['Movies']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOVIEREQUEST._serialized_start=23
  _MOVIEREQUEST._serialized_end=57
  _MOVIELIST._serialized_start=59
  _MOVIELIST._serialized_end=144
  _MOVIERESPONSE._serialized_start=146
  _MOVIERESPONSE._serialized_end=189
  _MOVIES._serialized_start=191
  _MOVIES._serialized_end=244
# @@protoc_insertion_point(module_scope)
