# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import movie_service_pb2 as movie__service__pb2


class MoviesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_movies = channel.unary_unary(
                '/Movies/get_movies',
                request_serializer=movie__service__pb2.MovieRequest.SerializeToString,
                response_deserializer=movie__service__pb2.MovieResponse.FromString,
                )


class MoviesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_movies(self, request, context):
        """Run method get_movies with MovieRequest parameter and return MovieResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MoviesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_movies': grpc.unary_unary_rpc_method_handler(
                    servicer.get_movies,
                    request_deserializer=movie__service__pb2.MovieRequest.FromString,
                    response_serializer=movie__service__pb2.MovieResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Movies', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Movies(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_movies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Movies/get_movies',
            movie__service__pb2.MovieRequest.SerializeToString,
            movie__service__pb2.MovieResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
